### ISSUE TITLE
jquery loading (from CDN or local filestore) for local builds with readthedocs theme doesn't work

### ISSUE THREAD

**Issue by ci5er** [tomchristie/mkdocs#324] opened 2015-01-10 03:55 UTC
To fix this, there will either need to be local copies of both the CDN hosted javascript files in the theme directory (which there currently are not), or http: needs to be explicated as the protocol handler.

**Comment by d0ugal** [comment] 2015-01-10 10:47
Duplicate of #143.

**Closed by d0ugal** 2015-01-10 10:47 UTC
