### ISSUE TITLE
Auto-reloading doesn't work (at least under OS X).

### ISSUE THREAD

**Issue by mrmachine** [tomchristie/mkdocs#214] opened 2014-11-12 22:48 UTC
Any time I save a change in the docs dir, I get this in the terminal:

```
Running at: http://127.0.0.1:8000/
Live reload enabled.
Hold ctrl+c to quit.
[13/Nov/2014 09:43:54] "GET / HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/tailee/.pyenv/versions/2.7.8/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/lib/python2.7/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/lib/python2.7/site-packages/watchdog/observers/api.py", line 367, in dispatch_events
    self._dispatch_event(event, watch)
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/lib/python2.7/site-packages/watchdog/observers/api.py", line 362, in _dispatch_event
    handler.dispatch(event)
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/lib/python2.7/site-packages/watchdog/events.py", line 322, in dispatch
    self.on_any_event(event)
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/src/mkdocs/mkdocs/serve.py", line 28, in on_any_event
    build(config, live_server=True)
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/src/mkdocs/mkdocs/build.py", line 229, in build
    utils.copy_media_files(config['docs_dir'], config['site_dir'])
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/src/mkdocs/mkdocs/utils.py", line 61, in copy_media_files
    copy_file(source_path, output_path)
  File "/Users/tailee/.virtualenvs/ixc-tech-wiki/src/mkdocs/mkdocs/utils.py", line 23, in copy_file
    shutil.copy(source_path, output_path)
  File "/Users/tailee/.pyenv/versions/2.7.8/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/Users/tailee/.pyenv/versions/2.7.8/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/var/folders/17/zt6gvrv948b48xnk_zxmw2l80000gp/T/tmpaMfswi/.git/objects/02/8d3b460a09ae1d3a857ef1126b4dd1faa2fb3e'
```

Seems like the file is being created with the wrong permissions, even though the directory has owner write permission:

```shell
$ ls -la /var/folders/17/zt6gvrv948b48xnk_zxmw2l80000gp/T/tmpaMfswi/.git/objects/02
total 8
drwxr-xr-x   3 tailee  staff   102 13 Nov 09:43 ./
drwxr-xr-x  93 tailee  staff  3162 13 Nov 09:43 ../
-r--r--r--   1 tailee  staff  3742 13 Nov 09:43 8d3b460a09ae1d3a857ef1126b4dd1faa2fb3e
```

I can fix it by first removing any existing file in the `copy_file()` function:

```python
def copy_file(source_path, output_path):
    """
    Copy source_path to output_path, making sure any parent directories exist.
    """
    output_dir = os.path.dirname(output_path)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    if os.path.exists(output_path):
        os.remove(output_path)
    shutil.copy(source_path, output_path)
```

But perhaps a better fix would be to create the file as writeable?

**Comment by ePirat** [comment] 2015-01-04 23:18
I can confirm this to be fixed with current master, at least I am not able to reproduce the issue, everything working fine.

**Comment by d0ugal** [comment] 2015-01-05 10:12
Thanks @ePirat - I'll close this for now and re-open if we get any new reports.

**Closed by d0ugal** 2015-01-05 10:12 UTC
Labels: Needs confirmation
