### ISSUE TITLE
Windows UTF-8 woes

### ISSUE THREAD

**Issue by johnstevenson** [tomchristie/mkdocs#362] opened 2015-03-10 16:39 UTC
Windows 8.1
Python 3.4.3
mkdocs 0.11.1

UTF-8 characters are not recognized, because system code-page character-mapping is being used: `cp1252.py`

Using this `mkdocs.yml`

```yml
site_name: “My Docs”
```
I get the following error:

> File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 19: character maps to \<undefined\>

Obviously, similar errors are returned if any of the `.md` files contain UTF-8 characters.

I have hacked a personal fix (I am not a Python dev) by changing https://github.com/tomchristie/mkdocs/blob/455c1a66dbc77960893ad371d76dae0fa59bfa96/mkdocs/build.py#L206

```
input_content = open(input_path, 'r', encoding='utf8').read()
```
and https://github.com/tomchristie/mkdocs/blob/455c1a66dbc77960893ad371d76dae0fa59bfa96/mkdocs/config.py#L80

```
with open(filename, 'r', encoding='utf8') as fp:
```
**Big BUT**
Now we get an error after using the `new` command to create the default files, because `index.md` contains a UTF-8 character (`c2 a0 NO-BREAK SPACE`) that the parser doesn't like :

>File "C:\Python34\lib\codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 348: invalid start byte

It is here: https://github.com/tomchristie/mkdocs/blob/455c1a66dbc77960893ad371d76dae0fa59bfa96/mkdocs/new.py#L19

```
## Project layout

    mkdocs.yml # The configuration file.
                ^
```

**Comment by LPGhatguy** [comment] 2015-03-16 23:13
I encountered similar issues running mkdocs locally with UTF-8 characters in my `.md` documents.

Surprisingly, ReadTheDocs doesn't have this issue, even when using mkdocs as the backend.

**Comment by zycbobby** [comment] 2015-03-17 04:28
I also encounter this problem recently when I try to build docs on the server. It works fine on Ubuntu 14.04 but not on Windows 8. I paste the error log here:

```shell
C:\Users\hr-admin\.hudson\jobs\Maven Build\workspace\updater-docs\current>python C:\Python34\Scripts\mkdocs-script.py build --clean
Cleaning site directory
Building documentation to directory: site
Traceback (most recent call last):
  File "C:\Python34\Scripts\mkdocs-script.py", line 9, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "C:\Python34\lib\site-packages\mkdocs\main.py", line 60, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "C:\Python34\lib\site-packages\mkdocs\main.py", line 36, in main
    build(config, clean_site_dir=clean_site_dir)
  File "C:\Python34\lib\site-packages\mkdocs\build.py", line 266, in build
    build_pages(config)
  File "C:\Python34\lib\site-packages\mkdocs\build.py", line 206, in build_pages

    input_content = open(input_path, 'r').read()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4634: character maps to <undefined>
```

**Comment by d0ugal** [comment] 2015-03-17 11:36
I'm not really able to support windows at the moment.

However, this appears to be a duplicate of #239.

**Closed by d0ugal** 2015-03-17 11:36 UTC
Labels: Bug

**Comment by kasperkowalski** [comment] 2015-05-26 21:29
I was able to fix the same issue but it's not a problem with mkdocs rather with livereload lib.
I've described it here https://github.com/lepture/python-livereload/issues/111
